# Generated by Django 3.2 on 2021-04-21 09:06

from django.db import migrations, models
import ds.models


class Migration(migrations.Migration):

    dependencies = [
        ('ds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='mood_config',
            field=models.JSONField(default=ds.models.get_default_moods),
        ),
    ]
